;; -*- indent-tabs-mode: nil; fill-column: 100 -*-

(define (->string x)
  (cond ((string? x))
        ((number? x) (number->string x))
        ((symbol? x) (symbol->string x))
        ((procedure? x) "#<procedure>")
        ((char? x) (string x))
        ((eq? x #t) "#t")
        ((eq? x #f) "#f")
        ((eq? x '()) "()")
        ((eq? x (unspecified)) "#!unspecified")
        ((eof-object? x) "#!eof")
        ((pair? x) ...)
        (else "#<weird>")))
